# Generated by Django 5.1.15 on 2026-10-02 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ticket", "Billet"),
                            ("organizer_access", "Accès Organisateur VIP"),
                        ],
                        default="ticket",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("moncash", "MonCash"),
                            ("natcash", "NatCash"),
                            ("stripe", "Carte bancaire (Stripe)"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=10,
                        verbose_name="mode de paiement",
                    ),
                ),
                (
                    "amount_htg",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="montant (HTG)"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="nombre de billets"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="référence"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("success", "Réussi"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "payer_detail",
                    models.CharField(
                        blank=True,
                        help_text="Numéro masqué ou e-mail du payeur (jamais de données de carte complètes).",
                        max_length=120,
                        verbose_name="détail payeur",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="events.event",
                        verbose_name="événement",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="events.guest",
                        verbose_name="invité",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
                "verbose_name_plural": "paiements",
                "ordering": ["-created_at"],
            },
        ),
    ]
