# Generated by Django 5.1.15 on 2026-10-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_accept_contributions"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ticket", "Billet"),
                    ("organizer_access", "Accès Organisateur VIP"),
                    ("contribution", "Contribution en argent"),
                ],
                default="ticket",
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_htg",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="montant (HTG)"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="petit mot"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="events.event",
                        verbose_name="événement",
                    ),
                ),
                (
                    "guest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contribution",
                        to="events.guest",
                        verbose_name="invité",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contribution",
                        to="payments.payment",
                        verbose_name="paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "contribution",
                "verbose_name_plural": "contributions",
                "ordering": ["-created_at"],
            },
        ),
    ]
