# Generated by Django 5.1.15 on 2026-10-02 18:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "event_type",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Privé")],
                        default="private",
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("draft", "Brouillon"),
                            ("cancelled", "Annulé"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("time", models.TimeField(verbose_name="heure")),
                (
                    "venue",
                    models.CharField(max_length=255, verbose_name="lieu (adresse)"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="longitude"),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        default=100, verbose_name="nombre maximum d'invités"
                    ),
                ),
                (
                    "allow_companions",
                    models.BooleanField(
                        default=False, verbose_name="accompagnants autorisés"
                    ),
                ),
                (
                    "max_companions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="accompagnants maximum par invité"
                    ),
                ),
                (
                    "evaluation_delay_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="délai d'évaluation (jours)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/covers/",
                        verbose_name="photo de couverture",
                    ),
                ),
                (
                    "cover_video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="events/videos/",
                        verbose_name="vidéo de couverture",
                    ),
                ),
                (
                    "price_htg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Laisser vide si l'événement est gratuit.",
                        max_digits=10,
                        null=True,
                        verbose_name="prix du billet (HTG)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "événement",
                "verbose_name_plural": "événements",
                "ordering": ["date", "time"],
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Présent"),
                            ("declined", "Absent"),
                            ("maybe", "Peut-être"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "companions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="accompagnants"
                    ),
                ),
                (
                    "sent_via",
                    models.CharField(
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp")],
                        default="whatsapp",
                        max_length=10,
                        verbose_name="canal d'envoi",
                    ),
                ),
                (
                    "magic_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="lien magique",
                    ),
                ),
                (
                    "invitation_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="invitation envoyée le"
                    ),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="répondu le"
                    ),
                ),
                (
                    "wants_gift",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="souhaite offrir un cadeau"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="events.event",
                        verbose_name="événement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="compte lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "invité",
                "verbose_name_plural": "invités",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EventEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stars",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="note",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="commentaire")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "évaluation",
                "verbose_name_plural": "évaluations",
                "unique_together": {("event", "user")},
            },
        ),
    ]
