# Generated by Django 5.1.15 on 2026-10-02 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/groups/",
                        verbose_name="photo de couverture",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "groupe d'événements",
                "verbose_name_plural": "groupes d'événements",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Facultatif : regroupe cet événement avec d'autres (cérémonie, réception, brunch...).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventgroup",
                verbose_name="groupe d'événements",
            ),
        ),
    ]
