# Generated by Django 5.1.15 on 2026-10-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=60, unique=True, verbose_name="nom"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=70,
                        unique=True,
                        verbose_name="identifiant dans l'adresse",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        default="bi-calendar2-event",
                        max_length=50,
                        verbose_name="icône",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie d'événements",
                "verbose_name_plural": "catégories d'événements",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventcategory",
                verbose_name="catégorie",
            ),
        ),
    ]
