# Generated by Django 5.1.15 on 2026-10-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="language",
            field=models.CharField(
                choices=[
                    ("fr", "Français"),
                    ("en", "English"),
                    ("ht", "Kreyòl ayisyen"),
                ],
                default="fr",
                max_length=5,
                verbose_name="langue de l'invitation",
            ),
        ),
    ]
