# Generated by Django 5.1.15 on 2026-10-03 20:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_guest_entry_code_checkin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="reminder_every_days",
            field=models.PositiveSmallIntegerField(
                default=7, verbose_name="puis tous les (jours)"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="reminder_first_after_days",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="première relance après (jours)"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="reminder_hour",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="heure d'envoi des relances"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="reminder_max",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="relances maximum par invité"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="reminders_auto",
            field=models.BooleanField(
                default=False, verbose_name="envoi automatique des relances par e-mail"
            ),
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp")],
                        max_length=10,
                        verbose_name="canal",
                    ),
                ),
                (
                    "automatic",
                    models.BooleanField(default=False, verbose_name="automatique"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="envoyée le"
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="events.guest",
                        verbose_name="invité",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "relance",
                "verbose_name_plural": "relances",
                "ordering": ["-sent_at", "-pk"],
            },
        ),
    ]
