# Generated by Django 5.1.15 on 2026-10-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_seating_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="accept_contributions",
            field=models.BooleanField(
                default=False,
                help_text="Les invités peuvent contribuer en argent (MonCash ou NatCash) à la place d'un cadeau.",
                verbose_name="accepter les contributions en argent",
            ),
        ),
    ]
