# Generated by Django 5.1.15 on 2026-10-04 01:01

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_accept_contributions"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="thanks_message",
            field=models.TextField(blank=True, verbose_name="message de remerciement"),
        ),
        migrations.AddField(
            model_name="event",
            name="thanks_published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="remerciements publiés le"
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="thanks_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="remerciement envoyé le"
            ),
        ),
        migrations.CreateModel(
            name="AlbumPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=events.models.album_path, verbose_name="photo"
                    ),
                ),
                (
                    "thumb",
                    models.ImageField(
                        upload_to=events.models.album_path, verbose_name="miniature"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ajoutée le"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="events.event",
                        verbose_name="événement",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="album_photos",
                        to="events.guest",
                        verbose_name="ajoutée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo de l'album",
                "verbose_name_plural": "photos de l'album",
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
