# Generated by Django 5.1.15 on 2026-10-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_thanks_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcategory",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="categories/", verbose_name="photo de la tuile"
            ),
        ),
    ]
