# Generated by Django 5.1.15 on 2026-10-04 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_category_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["event", "-created_at"], name="checkin_event_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "status", "date"],
                name="event_public_upcoming_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="event_date_idx"),
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(
                fields=["event", "status"], name="guest_event_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(fields=["event", "name"], name="guest_event_name_idx"),
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(fields=["-replied_at"], name="guest_replied_idx"),
        ),
        migrations.AddIndex(
            model_name="guest",
            index=models.Index(fields=["email"], name="guest_email_idx"),
        ),
    ]
