# Generated by Django 5.1.15 on 2026-10-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "contact",
                    models.CharField(
                        max_length=120, verbose_name="e-mail ou téléphone"
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("invitation", "Mon invitation ou ma réponse"),
                            ("gift", "Les cadeaux"),
                            ("payment", "Un paiement ou un billet"),
                            ("vip", "L'accès Organisateur VIP"),
                            ("organize", "Organiser mon événement"),
                            ("other", "Autre question"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="sujet",
                    ),
                ),
                ("message", models.TextField(max_length=2000, verbose_name="message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("in_progress", "En cours"),
                            ("resolved", "Résolue"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="reçue le"),
                ),
            ],
            options={
                "verbose_name": "demande d'aide",
                "verbose_name_plural": "demandes d'aide",
                "ordering": ["-created_at"],
            },
        ),
    ]
