# Generated by Django 5.1.15 on 2026-10-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_help_requests"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(fields=["-created_at"], name="contact_created_idx"),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(fields=["is_read"], name="contact_read_idx"),
        ),
        migrations.AddIndex(
            model_name="helprequest",
            index=models.Index(
                fields=["status", "-created_at"], name="help_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["is_published", "-created_at"], name="review_published_idx"
            ),
        ),
    ]
