# Generated by Django 5.1.15 on 2026-10-05 15:58

from django.db import migrations, models


# Avis d'exemple que l'ancien jeu de démonstration (seed_demo) publiait : ce ne sont pas de vrais clients.
EXEMPLES = [
    ("Roseline A.", "Nos invités ont répondu en quelques minutes depuis WhatsApp."),
    ("Patrick É.", "Tableau de bord clair, suivi en direct des présences"),
    ("Claudine J.", "Très pratique de pouvoir payer avec MonCash."),
]


def masquer_avis_exemple(apps, schema_editor):
    Review = apps.get_model("core", "Review")
    for name, debut in EXEMPLES:
        Review.objects.filter(name=name, text__startswith=debut).update(is_published=False)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_index_recherches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Un avis envoyé depuis le site attend la validation de l'équipe avant d'apparaître sur l'accueil.",
                verbose_name="publié",
            ),
        ),
        migrations.RunPython(masquer_avis_exemple, migrations.RunPython.noop),
    ]
