# Generated by Django 5.1.15 on 2026-10-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_avis_valides_par_equipe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("signup", "Inscription"),
                            ("payment", "Paiement"),
                            ("help", "Demande d'aide"),
                            ("contact", "Message de contact"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=200, verbose_name="détail"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="utm_source"
                    ),
                ),
                (
                    "medium",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="utm_medium"
                    ),
                ),
                (
                    "campaign",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="utm_campaign"
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="utm_term"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="utm_content"
                    ),
                ),
                (
                    "landing_page",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="page d'arrivée"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="date"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "provenance",
                "verbose_name_plural": "provenances",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="attribution_created_idx"
                    ),
                    models.Index(
                        fields=["source", "campaign"], name="attribution_source_idx"
                    ),
                ],
            },
        ),
    ]
