# Generated by Django 5.1.15 on 2026-10-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_provenance_utm"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogoVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Par exemple : Noël 2026, Saint-Valentin.",
                        max_length=80,
                        verbose_name="nom",
                    ),
                ),
                (
                    "preset",
                    models.CharField(
                        choices=[
                            ("original", "Violet (original)"),
                            ("or", "Or"),
                            ("rose", "Rose"),
                            ("rouge", "Rouge"),
                            ("bleu", "Bleu"),
                            ("vert", "Vert"),
                            ("perso", "Mon propre fichier"),
                        ],
                        default="or",
                        max_length=12,
                        verbose_name="couleur",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Seulement pour « Mon propre fichier » : PNG à fond transparent.",
                        upload_to="logos/",
                        verbose_name="logo pour fond clair",
                    ),
                ),
                (
                    "image_dark",
                    models.ImageField(
                        blank=True,
                        help_text="Facultatif : sinon le logo pour fond clair est utilisé partout.",
                        upload_to="logos/",
                        verbose_name="logo pour fond sombre",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="du")),
                ("end_date", models.DateField(verbose_name="au")),
                ("is_active", models.BooleanField(default=True, verbose_name="activé")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "version du logo",
                "verbose_name_plural": "versions du logo",
                "ordering": ["-start_date", "-pk"],
            },
        ),
    ]
