# Generated by Django 5.1.15 on 2026-10-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_versions_du_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="jour")),
                ("page", models.CharField(max_length=80, verbose_name="page")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="vues")),
            ],
            options={
                "verbose_name": "pages vues",
                "verbose_name_plural": "pages vues",
                "ordering": ["-day", "page"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "page"), name="pageview_day_page_unique"
                    )
                ],
            },
        ),
    ]
