# Generated by Django 5.1.15 on 2026-10-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="nom du cadeau"),
                ),
                (
                    "icon_name",
                    models.CharField(
                        choices=[
                            ("bi-gift", "Cadeau"),
                            ("bi-cup-hot", "Service à thé / café"),
                            ("bi-cup-straw", "Verres"),
                            ("bi-egg-fried", "Cuisine"),
                            ("bi-house-heart", "Maison"),
                            ("bi-lamp", "Lampe"),
                            ("bi-tv", "Télévision"),
                            ("bi-speaker", "Enceinte"),
                            ("bi-camera", "Appareil photo"),
                            ("bi-laptop", "Ordinateur"),
                            ("bi-phone", "Telephone"),
                            ("bi-headphones", "Casque audio"),
                            ("bi-basket", "Panier"),
                            ("bi-flower1", "Fleurs"),
                            ("bi-airplane", "Voyage"),
                            ("bi-suitcase", "Bagages"),
                            ("bi-bicycle", "Vélo"),
                            ("bi-book", "Livre"),
                            ("bi-palette", "Décoration"),
                            ("bi-wallet2", "Enveloppe"),
                            ("bi-gem", "Bijou"),
                            ("bi-watch", "Montre"),
                            ("bi-music-note-beamed", "Musique"),
                            ("bi-heart", "Coup de cœur"),
                        ],
                        default="bi-gift",
                        max_length=50,
                        verbose_name="icône",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="quantité"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts",
                        to="events.event",
                        verbose_name="événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "cadeau",
                "verbose_name_plural": "cadeaux",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GiftClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="choisi le"),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="gifts.gift",
                        verbose_name="cadeau",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gift_claims",
                        to="events.guest",
                        verbose_name="invité",
                    ),
                ),
            ],
            options={
                "verbose_name": "cadeau choisi",
                "verbose_name_plural": "cadeaux choisis",
                "ordering": ["claimed_at"],
                "unique_together": {("gift", "guest")},
            },
        ),
    ]
