# Generated by Django 5.1.15 on 2026-10-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="titre")),
                (
                    "icon_name",
                    models.CharField(
                        default="bi-megaphone", max_length=50, verbose_name="icône"
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="ads/", verbose_name="image"
                    ),
                ),
                ("sponsor_link", models.URLField(verbose_name="lien du sponsor")),
                (
                    "skip_after_seconds",
                    models.PositiveIntegerField(
                        default=5, verbose_name="passer après (secondes)"
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0, verbose_name="vues")),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="clics"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "show_after_reply",
                    models.BooleanField(
                        default=True,
                        help_text="Si coché, la publicité fait partie de la séquence affichée après une réponse.",
                        verbose_name="afficher après la réponse d'un invité",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ordre d'affichage"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "publicité",
                "verbose_name_plural": "publicités",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
