# Generated by Django 5.1.15 on 2026-10-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ad",
            index=models.Index(
                fields=["is_active", "order"], name="ad_active_order_idx"
            ),
        ),
    ]
