# Generated by Django 5.1.15 on 2026-10-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_index_recherches"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Jouée sans le son, en boucle. L'image ci-dessus s'affiche avant qu'elle démarre.",
                null=True,
                upload_to="ads/videos/",
                verbose_name="vidéo",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Utilisé seulement s'il n'y a pas de fichier vidéo.",
                verbose_name="lien d'une vidéo YouTube ou Facebook",
            ),
        ),
    ]
