# Generated by Django 5.1.15 on 2026-10-05 17:23

from django.db import migrations, models


def keep_existing_ads_visible(apps, schema_editor):
    """Les publicités déjà en ligne avant cette étape restent visibles (marquées payées)."""
    apps.get_model("ads", "Ad").objects.update(is_paid=True)


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="advertiser",
            field=models.CharField(
                blank=True,
                help_text="Le partenaire ou la personne qui paie cette publicité.",
                max_length=150,
                verbose_name="annonceur",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="advertiser_phone",
            field=models.CharField(
                blank=True,
                max_length=30,
                verbose_name="téléphone ou WhatsApp de l'annonceur",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="amount_htg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="montant payé (HTG)",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Après cette date, la publicité ne s'affiche plus. Vide : sans fin.",
                null=True,
                verbose_name="fin de diffusion",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="is_paid",
            field=models.BooleanField(
                default=False,
                help_text="La publicité n'apparaît sur le site qu'une fois cochée « payée ».",
                verbose_name="payée",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="début de diffusion"
            ),
        ),
        migrations.RunPython(keep_existing_ads_visible, migrations.RunPython.noop),
    ]
