# Generated by Django 5.1.15 on 2026-10-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fr", "Français"),
                    ("en", "English"),
                    ("ht", "Kreyòl ayisyen"),
                ],
                max_length=5,
                verbose_name="langue",
            ),
        ),
    ]
